services:
  app:
    build: .
    ports:
      - "8888:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_DATABASE=calendar_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  js:
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - ./calendar.appli.web:/usr/src/app
    command: >
      sh -c "npm install -g serve && serve -s . -l 3333"
    ports:
      - "3333:3333"
  
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calendar_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
